enable_quirks: true
custom_quirks_path: config/custom_zha_quirks/
database_path: /config/zigbee.db 
zigpy_config:
  ota:
    enabled: true

    ikea_provider: true # Auto update Tr√•dfri devices
    ledvance_provider: true # Auto update LEDVANCE/OSRAM devices
    salus_provider: true # Auto update SALUS/Computime devices
    inovelli_provider: true # Auto update INOVELLI devices
    thirdreality_provider: true

    z2m_remote_index: "https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/index.json"

    # Periodically send out a network-wide (including end devices!) image notification
    broadcast_enabled: true
    broadcast_initial_delay: 14400
    broadcast_interval: 14400

device_config:
  a4:c1:38:69:72:b0:a6:9e-1:
    type: "switch"
  a4:c1:38:69:72:b0:a6:9e-2:
    type: "switch"
  a4:c1:38:69:72:b0:a6:9e-3:
    type: "switch"
  a4:c1:38:69:72:b0:a6:9e-4:
    type: "switch"
  a4:c1:38:69:72:b0:a6:9e-5:
    type: "switch"